# Generated by Django 4.2.11 on 2024-04-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sem_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_creat', models.DateTimeField()),
                ('date_edit', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_app.author')),
            ],
        ),
    ]
