# Generated by Django 5.0.4 on 2024-04-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TossCoin',
        ),
    ]
