# Generated by Django 4.2.11 on 2024-04-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem_app', '0003_client_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
