# Generated by Django 4.2.11 on 2024-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem_app', '0004_rename_adress_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
    ]
